### PR TITLE
Adds '%' as sentinel to support double-quote aliases

### PR DESCRIPTION
**Pull request by lylemoffitt**
This simply adds the percent symbol as an optional sentinel for alias command strings.

### CODE REVIEW

**Comment by bfontaine** [comment]
Do you mind mentioning it in the docs as well? Thanks!

**Comment by lylemoffitt** [comment]
The docs are updated with usage for '%' now.

**Comment by lylemoffitt** [comment]
I also updated the usage of quotes to specifically mention when shell expansion happens. Hopefully that will help clear this up.

**Comment by lylemoffitt** [comment]
@bfontaine Anything else this needs in order to be merged?

**Comment by lylemoffitt** [comment]
@bfontaine Fixed the notes problem mentioned in the other PR here as well.

**Comment by bfontaine** [comment]
Thanks @lylemoffitt; I’ll merge when I’m home (I’m not on my personal machine right now).

**Comment by bfontaine** [comment]
Merged! Thanks again @lylemoffitt! 🎉

**Pull request closed without merging**
