### PR TITLE
better reserved list

### PR DESCRIPTION
**Pull request by xu-cheng**
cc @bfontaine

### CODE REVIEW

**Comment by bfontaine** [comment]
:+1:

**Comment by xu-cheng** [comment]
I updated a little to make sure it won't overwrite existed external commands.

**Comment by xu-cheng** [comment]
@bfontaine Any comment on newer version PR?

**Comment by bfontaine** [comment]
@xu-cheng Sorry I didn’t respond but it’s ok you can merge it :smile:

**Pull request merged**
